import * as ace from "ace-builds";

import "./theme";

import extBeautify from "ace-builds/src-noconflict/ext-beautify?url";
ace.config.setModuleUrl("ace/ext/beautify", extBeautify);
import extCodeLens from "ace-builds/src-noconflict/ext-code_lens?url";
ace.config.setModuleUrl("ace/ext/code_lens", extCodeLens);
import extCommand_bar from "ace-builds/src-noconflict/ext-command_bar?url";
ace.config.setModuleUrl("ace/ext/command_bar", extCommand_bar);
import extElasticTabstopsLite from "ace-builds/src-noconflict/ext-elastic_tabstops_lite?url";
ace.config.setModuleUrl(
	"ace/ext/elastic_tabstops_lite",
	extElasticTabstopsLite
);
import extEmmet from "ace-builds/src-noconflict/ext-emmet?url";
ace.config.setModuleUrl("ace/ext/emmet", extEmmet);
import extErrorMarker from "ace-builds/src-noconflict/ext-error_marker?url";
ace.config.setModuleUrl("ace/ext/error_marker", extErrorMarker);
import extHardwrap from "ace-builds/src-noconflict/ext-hardwrap?url";
ace.config.setModuleUrl("ace/ext/hardwrap", extHardwrap);
import extInlineAutocomplete from "ace-builds/src-noconflict/ext-inline_autocomplete?url";
ace.config.setModuleUrl("ace/ext/inline_autocomplete", extInlineAutocomplete);
import extKeybindingMenu from "ace-builds/src-noconflict/ext-keybinding_menu?url";
ace.config.setModuleUrl("ace/ext/keybinding_menu", extKeybindingMenu);
import extLanguageTools from "ace-builds/src-noconflict/ext-language_tools?url";
ace.config.setModuleUrl("ace/ext/language_tools", extLanguageTools);
import extLinking from "ace-builds/src-noconflict/ext-linking?url";
ace.config.setModuleUrl("ace/ext/linking", extLinking);
import extModelist from "ace-builds/src-noconflict/ext-modelist?url";
ace.config.setModuleUrl("ace/ext/modelist", extModelist);
import extOptions from "ace-builds/src-noconflict/ext-options?url";
ace.config.setModuleUrl("ace/ext/options", extOptions);
import extPrompt from "ace-builds/src-noconflict/ext-prompt?url";
ace.config.setModuleUrl("ace/ext/prompt", extPrompt);
import extRtl from "ace-builds/src-noconflict/ext-rtl?url";
ace.config.setModuleUrl("ace/ext/rtl", extRtl);
import extSearchbox from "ace-builds/src-noconflict/ext-searchbox?url";
ace.config.setModuleUrl("ace/ext/searchbox", extSearchbox);
import extSettingsMenu from "ace-builds/src-noconflict/ext-settings_menu?url";
ace.config.setModuleUrl("ace/ext/settings_menu", extSettingsMenu);
import extSpellcheck from "ace-builds/src-noconflict/ext-spellcheck?url";
ace.config.setModuleUrl("ace/ext/spellcheck", extSpellcheck);
import extSplit from "ace-builds/src-noconflict/ext-split?url";
ace.config.setModuleUrl("ace/ext/split", extSplit);
import extStaticHighlight from "ace-builds/src-noconflict/ext-static_highlight?url";
ace.config.setModuleUrl("ace/ext/static_highlight", extStaticHighlight);
import extStatusbar from "ace-builds/src-noconflict/ext-statusbar?url";
ace.config.setModuleUrl("ace/ext/statusbar", extStatusbar);
import extTextarea from "ace-builds/src-noconflict/ext-textarea?url";
ace.config.setModuleUrl("ace/ext/textarea", extTextarea);
import extThemelist from "ace-builds/src-noconflict/ext-themelist?url";
ace.config.setModuleUrl("ace/ext/themelist", extThemelist);
import extWhitespace from "ace-builds/src-noconflict/ext-whitespace?url";
ace.config.setModuleUrl("ace/ext/whitespace", extWhitespace);

import emacs from "ace-builds/src-noconflict/keybinding-emacs?url";
ace.config.setModuleUrl("ace/keybinding/emacs", emacs);
import sublime from "ace-builds/src-noconflict/keybinding-sublime?url";
ace.config.setModuleUrl("ace/keybinding/sublime", sublime);
import vim from "ace-builds/src-noconflict/keybinding-vim?url";
ace.config.setModuleUrl("ace/keybinding/vim", vim);
import vscode from "ace-builds/src-noconflict/keybinding-vscode?url";
ace.config.setModuleUrl("ace/keybinding/vscode", vscode);

import modeAbapUrl from "ace-builds/src-noconflict/mode-abap?url";
ace.config.setModuleUrl("ace/mode/abap", modeAbapUrl);
import modeAbcUrl from "ace-builds/src-noconflict/mode-abc?url";
ace.config.setModuleUrl("ace/mode/abc", modeAbcUrl);
import modeActionscriptUrl from "ace-builds/src-noconflict/mode-actionscript?url";
ace.config.setModuleUrl("ace/mode/actionscript", modeActionscriptUrl);
import modeAdaUrl from "ace-builds/src-noconflict/mode-ada?url";
ace.config.setModuleUrl("ace/mode/ada", modeAdaUrl);
import modeAldaUrl from "ace-builds/src-noconflict/mode-alda?url";
ace.config.setModuleUrl("ace/mode/alda", modeAldaUrl);
import modeApacheConfUrl from "ace-builds/src-noconflict/mode-apache_conf?url";
ace.config.setModuleUrl("ace/mode/apache_conf", modeApacheConfUrl);
import modeApexUrl from "ace-builds/src-noconflict/mode-apex?url";
ace.config.setModuleUrl("ace/mode/apex", modeApexUrl);
import modeApplescriptUrl from "ace-builds/src-noconflict/mode-applescript?url";
ace.config.setModuleUrl("ace/mode/applescript", modeApplescriptUrl);
import modeAqlUrl from "ace-builds/src-noconflict/mode-aql?url";
ace.config.setModuleUrl("ace/mode/aql", modeAqlUrl);
import modeAsciidocUrl from "ace-builds/src-noconflict/mode-asciidoc?url";
ace.config.setModuleUrl("ace/mode/asciidoc", modeAsciidocUrl);
import modeAslUrl from "ace-builds/src-noconflict/mode-asl?url";
ace.config.setModuleUrl("ace/mode/asl", modeAslUrl);
import modeAssemblyX86Url from "ace-builds/src-noconflict/mode-assembly_x86?url";
ace.config.setModuleUrl("ace/mode/assembly_x86", modeAssemblyX86Url);
import modeAutohotkeyUrl from "ace-builds/src-noconflict/mode-autohotkey?url";
ace.config.setModuleUrl("ace/mode/autohotkey", modeAutohotkeyUrl);
import modeBatchfileUrl from "ace-builds/src-noconflict/mode-batchfile?url";
ace.config.setModuleUrl("ace/mode/batchfile", modeBatchfileUrl);
import modeC9searchUrl from "ace-builds/src-noconflict/mode-c9search?url";
ace.config.setModuleUrl("ace/mode/c9search", modeC9searchUrl);
import modeCirruUrl from "ace-builds/src-noconflict/mode-cirru?url";
ace.config.setModuleUrl("ace/mode/cirru", modeCirruUrl);
import modeClojureUrl from "ace-builds/src-noconflict/mode-clojure?url";
ace.config.setModuleUrl("ace/mode/clojure", modeClojureUrl);
import modeCobolUrl from "ace-builds/src-noconflict/mode-cobol?url";
ace.config.setModuleUrl("ace/mode/cobol", modeCobolUrl);
import modeCoffeeUrl from "ace-builds/src-noconflict/mode-coffee?url";
ace.config.setModuleUrl("ace/mode/coffee", modeCoffeeUrl);
import modeColdfusionUrl from "ace-builds/src-noconflict/mode-coldfusion?url";
ace.config.setModuleUrl("ace/mode/coldfusion", modeColdfusionUrl);
import modeCrystalUrl from "ace-builds/src-noconflict/mode-crystal?url";
ace.config.setModuleUrl("ace/mode/crystal", modeCrystalUrl);
import modeCsharpUrl from "ace-builds/src-noconflict/mode-csharp?url";
ace.config.setModuleUrl("ace/mode/csharp", modeCsharpUrl);
import modeCsoundDocumentUrl from "ace-builds/src-noconflict/mode-csound_document?url";
ace.config.setModuleUrl("ace/mode/csound_document", modeCsoundDocumentUrl);
import modeCsoundOrchestraUrl from "ace-builds/src-noconflict/mode-csound_orchestra?url";
ace.config.setModuleUrl("ace/mode/csound_orchestra", modeCsoundOrchestraUrl);
import modeCsoundCcoreUrl from "ace-builds/src-noconflict/mode-csound_score?url";
ace.config.setModuleUrl("ace/mode/csound_score", modeCsoundCcoreUrl);
import modeCspUrl from "ace-builds/src-noconflict/mode-csp?url";
ace.config.setModuleUrl("ace/mode/csp", modeCspUrl);
import modeCssUrl from "ace-builds/src-noconflict/mode-css?url";
ace.config.setModuleUrl("ace/mode/css", modeCssUrl);
import modeCUrlyUrl from "ace-builds/src-noconflict/mode-curly?url";
ace.config.setModuleUrl("ace/mode/curly", modeCUrlyUrl);
import modeC_cppUrl from "ace-builds/src-noconflict/mode-c_cpp?url";
ace.config.setModuleUrl("ace/mode/c_cpp", modeC_cppUrl);
import modeDUrl from "ace-builds/src-noconflict/mode-d?url";
ace.config.setModuleUrl("ace/mode/d", modeDUrl);
import modeDartUrl from "ace-builds/src-noconflict/mode-dart?url";
ace.config.setModuleUrl("ace/mode/dart", modeDartUrl);
import modeDiffUrl from "ace-builds/src-noconflict/mode-diff?url";
ace.config.setModuleUrl("ace/mode/diff", modeDiffUrl);
import modeDjangoUrl from "ace-builds/src-noconflict/mode-django?url";
ace.config.setModuleUrl("ace/mode/django", modeDjangoUrl);
import modeDockerfileUrl from "ace-builds/src-noconflict/mode-dockerfile?url";
ace.config.setModuleUrl("ace/mode/dockerfile", modeDockerfileUrl);
import modeDotUrl from "ace-builds/src-noconflict/mode-dot?url";
ace.config.setModuleUrl("ace/mode/dot", modeDotUrl);
import modeDroolsUrl from "ace-builds/src-noconflict/mode-drools?url";
ace.config.setModuleUrl("ace/mode/drools", modeDroolsUrl);
import modeEdifactUrl from "ace-builds/src-noconflict/mode-edifact?url";
ace.config.setModuleUrl("ace/mode/edifact", modeEdifactUrl);
import modeEiffelUrl from "ace-builds/src-noconflict/mode-eiffel?url";
ace.config.setModuleUrl("ace/mode/eiffel", modeEiffelUrl);
import modeEjsUrl from "ace-builds/src-noconflict/mode-ejs?url";
ace.config.setModuleUrl("ace/mode/ejs", modeEjsUrl);
import modeElixirUrl from "ace-builds/src-noconflict/mode-elixir?url";
ace.config.setModuleUrl("ace/mode/elixir", modeElixirUrl);
import modeElmUrl from "ace-builds/src-noconflict/mode-elm?url";
ace.config.setModuleUrl("ace/mode/elm", modeElmUrl);
import modeErlangUrl from "ace-builds/src-noconflict/mode-erlang?url";
ace.config.setModuleUrl("ace/mode/erlang", modeErlangUrl);
import modeForthUrl from "ace-builds/src-noconflict/mode-forth?url";
ace.config.setModuleUrl("ace/mode/forth", modeForthUrl);
import modeFortranUrl from "ace-builds/src-noconflict/mode-fortran?url";
ace.config.setModuleUrl("ace/mode/fortran", modeFortranUrl);
import modeFsharpUrl from "ace-builds/src-noconflict/mode-fsharp?url";
ace.config.setModuleUrl("ace/mode/fsharp", modeFsharpUrl);
import modeFslUrl from "ace-builds/src-noconflict/mode-fsl?url";
ace.config.setModuleUrl("ace/mode/fsl", modeFslUrl);
import modeFtlUrl from "ace-builds/src-noconflict/mode-ftl?url";
ace.config.setModuleUrl("ace/mode/ftl", modeFtlUrl);
import modeGcodeUrl from "ace-builds/src-noconflict/mode-gcode?url";
ace.config.setModuleUrl("ace/mode/gcode", modeGcodeUrl);
import modeGherkinUrl from "ace-builds/src-noconflict/mode-gherkin?url";
ace.config.setModuleUrl("ace/mode/gherkin", modeGherkinUrl);
import modeGitignoreUrl from "ace-builds/src-noconflict/mode-gitignore?url";
ace.config.setModuleUrl("ace/mode/gitignore", modeGitignoreUrl);
import modeGlslUrl from "ace-builds/src-noconflict/mode-glsl?url";
ace.config.setModuleUrl("ace/mode/glsl", modeGlslUrl);
import modeGobstonesUrl from "ace-builds/src-noconflict/mode-gobstones?url";
ace.config.setModuleUrl("ace/mode/gobstones", modeGobstonesUrl);
import modeGolangUrl from "ace-builds/src-noconflict/mode-golang?url";
ace.config.setModuleUrl("ace/mode/golang", modeGolangUrl);
import modeGraphqlschemaUrl from "ace-builds/src-noconflict/mode-graphqlschema?url";
ace.config.setModuleUrl("ace/mode/graphqlschema", modeGraphqlschemaUrl);
import modeGroovyUrl from "ace-builds/src-noconflict/mode-groovy?url";
ace.config.setModuleUrl("ace/mode/groovy", modeGroovyUrl);
import modeHamlUrl from "ace-builds/src-noconflict/mode-haml?url";
ace.config.setModuleUrl("ace/mode/haml", modeHamlUrl);
import modeHandlebarsUrl from "ace-builds/src-noconflict/mode-handlebars?url";
ace.config.setModuleUrl("ace/mode/handlebars", modeHandlebarsUrl);
import modeHaskellUrl from "ace-builds/src-noconflict/mode-haskell?url";
ace.config.setModuleUrl("ace/mode/haskell", modeHaskellUrl);
import modeHaskellCabalUrl from "ace-builds/src-noconflict/mode-haskell_cabal?url";
ace.config.setModuleUrl("ace/mode/haskell_cabal", modeHaskellCabalUrl);
import modeHaxeUrl from "ace-builds/src-noconflict/mode-haxe?url";
ace.config.setModuleUrl("ace/mode/haxe", modeHaxeUrl);
import modeHjsonUrl from "ace-builds/src-noconflict/mode-hjson?url";
ace.config.setModuleUrl("ace/mode/hjson", modeHjsonUrl);
import modeHtmlUrl from "ace-builds/src-noconflict/mode-html?url";
ace.config.setModuleUrl("ace/mode/html", modeHtmlUrl);
import modeHtmlElixirUrl from "ace-builds/src-noconflict/mode-html_elixir?url";
ace.config.setModuleUrl("ace/mode/html_elixir", modeHtmlElixirUrl);
import modeHtmlRubyUrl from "ace-builds/src-noconflict/mode-html_ruby?url";
ace.config.setModuleUrl("ace/mode/html_ruby", modeHtmlRubyUrl);
import modeIniUrl from "ace-builds/src-noconflict/mode-ini?url";
ace.config.setModuleUrl("ace/mode/ini", modeIniUrl);
import modeIoUrl from "ace-builds/src-noconflict/mode-io?url";
ace.config.setModuleUrl("ace/mode/io", modeIoUrl);
import modeIonUrl from "ace-builds/src-noconflict/mode-ion?url";
ace.config.setModuleUrl("ace/mode/ion", modeIonUrl);
import modeJackUrl from "ace-builds/src-noconflict/mode-jack?url";
ace.config.setModuleUrl("ace/mode/jack", modeJackUrl);
import modeJadeUrl from "ace-builds/src-noconflict/mode-jade?url";
ace.config.setModuleUrl("ace/mode/jade", modeJadeUrl);
import modeJavaUrl from "ace-builds/src-noconflict/mode-java?url";
ace.config.setModuleUrl("ace/mode/java", modeJavaUrl);
import modeJavascriptUrl from "ace-builds/src-noconflict/mode-javascript?url";
ace.config.setModuleUrl("ace/mode/javascript", modeJavascriptUrl);
import modeJsonUrl from "ace-builds/src-noconflict/mode-json?url";
ace.config.setModuleUrl("ace/mode/json", modeJsonUrl);
import modeJson5Url from "ace-builds/src-noconflict/mode-json5?url";
ace.config.setModuleUrl("ace/mode/json5", modeJson5Url);
import modeJsoniqUrl from "ace-builds/src-noconflict/mode-jsoniq?url";
ace.config.setModuleUrl("ace/mode/jsoniq", modeJsoniqUrl);
import modeJspUrl from "ace-builds/src-noconflict/mode-jsp?url";
ace.config.setModuleUrl("ace/mode/jsp", modeJspUrl);
import modeJssmUrl from "ace-builds/src-noconflict/mode-jssm?url";
ace.config.setModuleUrl("ace/mode/jssm", modeJssmUrl);
import modeJsxUrl from "ace-builds/src-noconflict/mode-jsx?url";
ace.config.setModuleUrl("ace/mode/jsx", modeJsxUrl);
import modeJuliaUrl from "ace-builds/src-noconflict/mode-julia?url";
ace.config.setModuleUrl("ace/mode/julia", modeJuliaUrl);
import modeKotlinUrl from "ace-builds/src-noconflict/mode-kotlin?url";
ace.config.setModuleUrl("ace/mode/kotlin", modeKotlinUrl);
import modeLatexUrl from "ace-builds/src-noconflict/mode-latex?url";
ace.config.setModuleUrl("ace/mode/latex", modeLatexUrl);
import modeLatteUrl from "ace-builds/src-noconflict/mode-latte?url";
ace.config.setModuleUrl("ace/mode/latte", modeLatteUrl);
import modeLessUrl from "ace-builds/src-noconflict/mode-less?url";
ace.config.setModuleUrl("ace/mode/less", modeLessUrl);
import modeLiquidUrl from "ace-builds/src-noconflict/mode-liquid?url";
ace.config.setModuleUrl("ace/mode/liquid", modeLiquidUrl);
import modeLispUrl from "ace-builds/src-noconflict/mode-lisp?url";
ace.config.setModuleUrl("ace/mode/lisp", modeLispUrl);
import modeLivescriptUrl from "ace-builds/src-noconflict/mode-livescript?url";
ace.config.setModuleUrl("ace/mode/livescript", modeLivescriptUrl);
import modeLogiqlUrl from "ace-builds/src-noconflict/mode-logiql?url";
ace.config.setModuleUrl("ace/mode/logiql", modeLogiqlUrl);
import modeLogtalkUrl from "ace-builds/src-noconflict/mode-logtalk?url";
ace.config.setModuleUrl("ace/mode/logtalk", modeLogtalkUrl);
import modeLslUrl from "ace-builds/src-noconflict/mode-lsl?url";
ace.config.setModuleUrl("ace/mode/lsl", modeLslUrl);
import modeLuaUrl from "ace-builds/src-noconflict/mode-lua?url";
ace.config.setModuleUrl("ace/mode/lua", modeLuaUrl);
import modeLuapageUrl from "ace-builds/src-noconflict/mode-luapage?url";
ace.config.setModuleUrl("ace/mode/luapage", modeLuapageUrl);
import modeLuceneUrl from "ace-builds/src-noconflict/mode-lucene?url";
ace.config.setModuleUrl("ace/mode/lucene", modeLuceneUrl);
import modeMakefileUrl from "ace-builds/src-noconflict/mode-makefile?url";
ace.config.setModuleUrl("ace/mode/makefile", modeMakefileUrl);
import modeMarkdownUrl from "ace-builds/src-noconflict/mode-markdown?url";
ace.config.setModuleUrl("ace/mode/markdown", modeMarkdownUrl);
import modeMaskUrl from "ace-builds/src-noconflict/mode-mask?url";
ace.config.setModuleUrl("ace/mode/mask", modeMaskUrl);
import modeMatlabUrl from "ace-builds/src-noconflict/mode-matlab?url";
ace.config.setModuleUrl("ace/mode/matlab", modeMatlabUrl);
import modeMazeUrl from "ace-builds/src-noconflict/mode-maze?url";
ace.config.setModuleUrl("ace/mode/maze", modeMazeUrl);
import modeMediawikiUrl from "ace-builds/src-noconflict/mode-mediawiki?url";
ace.config.setModuleUrl("ace/mode/mediawiki", modeMediawikiUrl);
import modeMelUrl from "ace-builds/src-noconflict/mode-mel?url";
ace.config.setModuleUrl("ace/mode/mel", modeMelUrl);
import modeMipsUrl from "ace-builds/src-noconflict/mode-mips?url";
ace.config.setModuleUrl("ace/mode/mips", modeMipsUrl);
import modeMixalUrl from "ace-builds/src-noconflict/mode-mixal?url";
ace.config.setModuleUrl("ace/mode/mixal", modeMixalUrl);
import modeMushcodeUrl from "ace-builds/src-noconflict/mode-mushcode?url";
ace.config.setModuleUrl("ace/mode/mushcode", modeMushcodeUrl);
import modeMysqlUrl from "ace-builds/src-noconflict/mode-mysql?url";
ace.config.setModuleUrl("ace/mode/mysql", modeMysqlUrl);
import modeNginxUrl from "ace-builds/src-noconflict/mode-nginx?url";
ace.config.setModuleUrl("ace/mode/nginx", modeNginxUrl);
import modeNimUrl from "ace-builds/src-noconflict/mode-nim?url";
ace.config.setModuleUrl("ace/mode/nim", modeNimUrl);
import modeNixUrl from "ace-builds/src-noconflict/mode-nix?url";
ace.config.setModuleUrl("ace/mode/nix", modeNixUrl);
import modeNsisUrl from "ace-builds/src-noconflict/mode-nsis?url";
ace.config.setModuleUrl("ace/mode/nsis", modeNsisUrl);
import modeNunjucksUrl from "ace-builds/src-noconflict/mode-nunjucks?url";
ace.config.setModuleUrl("ace/mode/nunjucks", modeNunjucksUrl);
import modeObjectivecUrl from "ace-builds/src-noconflict/mode-objectivec?url";
ace.config.setModuleUrl("ace/mode/objectivec", modeObjectivecUrl);
import modeOcamlUrl from "ace-builds/src-noconflict/mode-ocaml?url";
ace.config.setModuleUrl("ace/mode/ocaml", modeOcamlUrl);
import modePartiqlUrl from "ace-builds/src-noconflict/mode-partiql?url";
ace.config.setModuleUrl("ace/mode/partiql", modePartiqlUrl);
import modePascalUrl from "ace-builds/src-noconflict/mode-pascal?url";
ace.config.setModuleUrl("ace/mode/pascal", modePascalUrl);
import modePerlUrl from "ace-builds/src-noconflict/mode-perl?url";
ace.config.setModuleUrl("ace/mode/perl", modePerlUrl);
import modePgsqlUrl from "ace-builds/src-noconflict/mode-pgsql?url";
ace.config.setModuleUrl("ace/mode/pgsql", modePgsqlUrl);
import modePhpUrl from "ace-builds/src-noconflict/mode-php?url";
ace.config.setModuleUrl("ace/mode/php", modePhpUrl);
import modePhpLaravelBladeUrl from "ace-builds/src-noconflict/mode-php_laravel_blade?url";
ace.config.setModuleUrl("ace/mode/php_laravel_blade", modePhpLaravelBladeUrl);
import modePigUrl from "ace-builds/src-noconflict/mode-pig?url";
ace.config.setModuleUrl("ace/mode/pig", modePigUrl);
import modePlain_textUrl from "ace-builds/src-noconflict/mode-plain_text?url";
ace.config.setModuleUrl("ace/mode/plain_text", modePlain_textUrl);
import modePowershellUrl from "ace-builds/src-noconflict/mode-powershell?url";
ace.config.setModuleUrl("ace/mode/powershell", modePowershellUrl);
import modePraatUrl from "ace-builds/src-noconflict/mode-praat?url";
ace.config.setModuleUrl("ace/mode/praat", modePraatUrl);
import modePrismaUrl from "ace-builds/src-noconflict/mode-prisma?url";
ace.config.setModuleUrl("ace/mode/prisma", modePrismaUrl);
import modePrologUrl from "ace-builds/src-noconflict/mode-prolog?url";
ace.config.setModuleUrl("ace/mode/prolog", modePrologUrl);
import modePropertiesUrl from "ace-builds/src-noconflict/mode-properties?url";
ace.config.setModuleUrl("ace/mode/properties", modePropertiesUrl);
import modeProtobufUrl from "ace-builds/src-noconflict/mode-protobuf?url";
ace.config.setModuleUrl("ace/mode/protobuf", modeProtobufUrl);
import modePuppetUrl from "ace-builds/src-noconflict/mode-puppet?url";
ace.config.setModuleUrl("ace/mode/puppet", modePuppetUrl);
import modePythonUrl from "ace-builds/src-noconflict/mode-python?url";
ace.config.setModuleUrl("ace/mode/python", modePythonUrl);
import modeQmlUrl from "ace-builds/src-noconflict/mode-qml?url";
ace.config.setModuleUrl("ace/mode/qml", modeQmlUrl);
import modeRUrl from "ace-builds/src-noconflict/mode-r?url";
ace.config.setModuleUrl("ace/mode/r", modeRUrl);
import modeRakuUrl from "ace-builds/src-noconflict/mode-raku?url";
ace.config.setModuleUrl("ace/mode/raku", modeRakuUrl);
import modeRazorUrl from "ace-builds/src-noconflict/mode-razor?url";
ace.config.setModuleUrl("ace/mode/razor", modeRazorUrl);
import modeRdocUrl from "ace-builds/src-noconflict/mode-rdoc?url";
ace.config.setModuleUrl("ace/mode/rdoc", modeRdocUrl);
import modeRedUrl from "ace-builds/src-noconflict/mode-red?url";
ace.config.setModuleUrl("ace/mode/red", modeRedUrl);
import modeRedshiftUrl from "ace-builds/src-noconflict/mode-redshift?url";
ace.config.setModuleUrl("ace/mode/redshift", modeRedshiftUrl);
import modeRhtmlUrl from "ace-builds/src-noconflict/mode-rhtml?url";
ace.config.setModuleUrl("ace/mode/rhtml", modeRhtmlUrl);
import modeRobotUrl from "ace-builds/src-noconflict/mode-robot?url";
ace.config.setModuleUrl("ace/mode/robot", modeRobotUrl);
import modeRstUrl from "ace-builds/src-noconflict/mode-rst?url";
ace.config.setModuleUrl("ace/mode/rst", modeRstUrl);
import modeRubyUrl from "ace-builds/src-noconflict/mode-ruby?url";
ace.config.setModuleUrl("ace/mode/ruby", modeRubyUrl);
import modeRustUrl from "ace-builds/src-noconflict/mode-rust?url";
ace.config.setModuleUrl("ace/mode/rust", modeRustUrl);
import modeSacUrl from "ace-builds/src-noconflict/mode-sac?url";
ace.config.setModuleUrl("ace/mode/sac", modeSacUrl);
import modeSassUrl from "ace-builds/src-noconflict/mode-sass?url";
ace.config.setModuleUrl("ace/mode/sass", modeSassUrl);
import modeScadUrl from "ace-builds/src-noconflict/mode-scad?url";
ace.config.setModuleUrl("ace/mode/scad", modeScadUrl);
import modeScalaUrl from "ace-builds/src-noconflict/mode-scala?url";
ace.config.setModuleUrl("ace/mode/scala", modeScalaUrl);
import modeSchemeUrl from "ace-builds/src-noconflict/mode-scheme?url";
ace.config.setModuleUrl("ace/mode/scheme", modeSchemeUrl);
import modeScryptUrl from "ace-builds/src-noconflict/mode-scrypt?url";
ace.config.setModuleUrl("ace/mode/scrypt", modeScryptUrl);
import modeScssUrl from "ace-builds/src-noconflict/mode-scss?url";
ace.config.setModuleUrl("ace/mode/scss", modeScssUrl);
import modeShUrl from "ace-builds/src-noconflict/mode-sh?url";
ace.config.setModuleUrl("ace/mode/sh", modeShUrl);
import modeSjsUrl from "ace-builds/src-noconflict/mode-sjs?url";
ace.config.setModuleUrl("ace/mode/sjs", modeSjsUrl);
import modeSlimUrl from "ace-builds/src-noconflict/mode-slim?url";
ace.config.setModuleUrl("ace/mode/slim", modeSlimUrl);
import modeSmartyUrl from "ace-builds/src-noconflict/mode-smarty?url";
ace.config.setModuleUrl("ace/mode/smarty", modeSmartyUrl);
import modeSmithyUrl from "ace-builds/src-noconflict/mode-smithy?url";
ace.config.setModuleUrl("ace/mode/smithy", modeSmithyUrl);
import modeSnippetsUrl from "ace-builds/src-noconflict/mode-snippets?url";
ace.config.setModuleUrl("ace/mode/snippets", modeSnippetsUrl);
import modeSoy_templateUrl from "ace-builds/src-noconflict/mode-soy_template?url";
ace.config.setModuleUrl("ace/mode/soy_template", modeSoy_templateUrl);
import modeSpaceUrl from "ace-builds/src-noconflict/mode-space?url";
ace.config.setModuleUrl("ace/mode/space", modeSpaceUrl);
import modeSparqlUrl from "ace-builds/src-noconflict/mode-sparql?url";
ace.config.setModuleUrl("ace/mode/sparql", modeSparqlUrl);
import modeSqlUrl from "ace-builds/src-noconflict/mode-sql?url";
ace.config.setModuleUrl("ace/mode/sql", modeSqlUrl);
import modeSqlserverUrl from "ace-builds/src-noconflict/mode-sqlserver?url";
ace.config.setModuleUrl("ace/mode/sqlserver", modeSqlserverUrl);
import modeStylusUrl from "ace-builds/src-noconflict/mode-stylus?url";
ace.config.setModuleUrl("ace/mode/stylus", modeStylusUrl);
import modeSvgUrl from "ace-builds/src-noconflict/mode-svg?url";
ace.config.setModuleUrl("ace/mode/svg", modeSvgUrl);
import modeSwiftUrl from "ace-builds/src-noconflict/mode-swift?url";
ace.config.setModuleUrl("ace/mode/swift", modeSwiftUrl);
import modeTclUrl from "ace-builds/src-noconflict/mode-tcl?url";
ace.config.setModuleUrl("ace/mode/tcl", modeTclUrl);
import modeTerraformUrl from "ace-builds/src-noconflict/mode-terraform?url";
ace.config.setModuleUrl("ace/mode/terraform", modeTerraformUrl);
import modeTexUrl from "ace-builds/src-noconflict/mode-tex?url";
ace.config.setModuleUrl("ace/mode/tex", modeTexUrl);
import modeTextUrl from "ace-builds/src-noconflict/mode-text?url";
ace.config.setModuleUrl("ace/mode/text", modeTextUrl);
import modeTextileUrl from "ace-builds/src-noconflict/mode-textile?url";
ace.config.setModuleUrl("ace/mode/textile", modeTextileUrl);
import modeTomlUrl from "ace-builds/src-noconflict/mode-toml?url";
ace.config.setModuleUrl("ace/mode/toml", modeTomlUrl);
import modeTsxUrl from "ace-builds/src-noconflict/mode-tsx?url";
ace.config.setModuleUrl("ace/mode/tsx", modeTsxUrl);
import modeTurtleUrl from "ace-builds/src-noconflict/mode-turtle?url";
ace.config.setModuleUrl("ace/mode/turtle", modeTurtleUrl);
import modeTwigUrl from "ace-builds/src-noconflict/mode-twig?url";
ace.config.setModuleUrl("ace/mode/twig", modeTwigUrl);
import modeTypescriptUrl from "ace-builds/src-noconflict/mode-typescript?url";
ace.config.setModuleUrl("ace/mode/typescript", modeTypescriptUrl);
import modeValaUrl from "ace-builds/src-noconflict/mode-vala?url";
ace.config.setModuleUrl("ace/mode/vala", modeValaUrl);
import modeVbscriptUrl from "ace-builds/src-noconflict/mode-vbscript?url";
ace.config.setModuleUrl("ace/mode/vbscript", modeVbscriptUrl);
import modeVelocityUrl from "ace-builds/src-noconflict/mode-velocity?url";
ace.config.setModuleUrl("ace/mode/velocity", modeVelocityUrl);
import modeVerilogUrl from "ace-builds/src-noconflict/mode-verilog?url";
ace.config.setModuleUrl("ace/mode/verilog", modeVerilogUrl);
import modeVhdlUrl from "ace-builds/src-noconflict/mode-vhdl?url";
ace.config.setModuleUrl("ace/mode/vhdl", modeVhdlUrl);
import modeVisualforceUrl from "ace-builds/src-noconflict/mode-visualforce?url";
ace.config.setModuleUrl("ace/mode/visualforce", modeVisualforceUrl);
import modeWollokUrl from "ace-builds/src-noconflict/mode-wollok?url";
ace.config.setModuleUrl("ace/mode/wollok", modeWollokUrl);
import modeXmlUrl from "ace-builds/src-noconflict/mode-xml?url";
ace.config.setModuleUrl("ace/mode/xml", modeXmlUrl);
import modeXqueryUrl from "ace-builds/src-noconflict/mode-xquery?url";
ace.config.setModuleUrl("ace/mode/xquery", modeXqueryUrl);
import modeYamlUrl from "ace-builds/src-noconflict/mode-yaml?url";
ace.config.setModuleUrl("ace/mode/yaml", modeYamlUrl);
import modeZeekUrl from "ace-builds/src-noconflict/mode-zeek?url";
ace.config.setModuleUrl("ace/mode/zeek", modeZeekUrl);

import themeAmbiance from "ace-builds/src-noconflict/theme-ambiance?url";
ace.config.setModuleUrl("ace/theme/ambiance", themeAmbiance);
import themeChaos from "ace-builds/src-noconflict/theme-chaos?url";
ace.config.setModuleUrl("ace/theme/chaos", themeChaos);
import themeChrome from "ace-builds/src-noconflict/theme-chrome?url";
ace.config.setModuleUrl("ace/theme/chrome", themeChrome);
import themeCloud9Day from "ace-builds/src-noconflict/theme-cloud9_day?url";
ace.config.setModuleUrl("ace/theme/cloud9_day", themeCloud9Day);
import themeCloud9Night from "ace-builds/src-noconflict/theme-cloud9_night?url";
ace.config.setModuleUrl("ace/theme/cloud9_night", themeCloud9Night);
import themeCloud9NightLowColor from "ace-builds/src-noconflict/theme-cloud9_night_low_color?url";
ace.config.setModuleUrl(
	"ace/theme/cloud9_night_low_color",
	themeCloud9NightLowColor
);
import themeClouds from "ace-builds/src-noconflict/theme-clouds?url";
ace.config.setModuleUrl("ace/theme/clouds", themeClouds);
import themeCloudsMidnight from "ace-builds/src-noconflict/theme-clouds_midnight?url";
ace.config.setModuleUrl("ace/theme/clouds_midnight", themeCloudsMidnight);
import themeCobalt from "ace-builds/src-noconflict/theme-cobalt?url";
ace.config.setModuleUrl("ace/theme/cobalt", themeCobalt);
import themeCrimsonEditor from "ace-builds/src-noconflict/theme-crimson_editor?url";
ace.config.setModuleUrl("ace/theme/crimson_editor", themeCrimsonEditor);
import themeDawn from "ace-builds/src-noconflict/theme-dawn?url";
ace.config.setModuleUrl("ace/theme/dawn", themeDawn);
import themeDracula from "ace-builds/src-noconflict/theme-dracula?url";
ace.config.setModuleUrl("ace/theme/dracula", themeDracula);
import themeDreamweaver from "ace-builds/src-noconflict/theme-dreamweaver?url";
ace.config.setModuleUrl("ace/theme/dreamweaver", themeDreamweaver);
import themeEclipse from "ace-builds/src-noconflict/theme-eclipse?url";
ace.config.setModuleUrl("ace/theme/eclipse", themeEclipse);
import themeGithub from "ace-builds/src-noconflict/theme-github?url";
ace.config.setModuleUrl("ace/theme/github", themeGithub);
import themeGithubDark from "ace-builds/src-noconflict/theme-github_dark?url";
ace.config.setModuleUrl("ace/theme/github_dark", themeGithubDark);
import themeGob from "ace-builds/src-noconflict/theme-gob?url";
ace.config.setModuleUrl("ace/theme/gob", themeGob);
import themeGruvbox from "ace-builds/src-noconflict/theme-gruvbox?url";
ace.config.setModuleUrl("ace/theme/gruvbox", themeGruvbox);
import themeGruvboxDarkHard from "ace-builds/src-noconflict/theme-gruvbox_dark_hard?url";
ace.config.setModuleUrl("ace/theme/gruvbox_dark_hard", themeGruvboxDarkHard);
import themeGruvboxLightHard from "ace-builds/src-noconflict/theme-gruvbox_light_hard?url";
ace.config.setModuleUrl("ace/theme/gruvbox_light_hard", themeGruvboxLightHard);
import themeIdleFingers from "ace-builds/src-noconflict/theme-idle_fingers?url";
ace.config.setModuleUrl("ace/theme/idle_fingers", themeIdleFingers);
import themeIplastic from "ace-builds/src-noconflict/theme-iplastic?url";
ace.config.setModuleUrl("ace/theme/iplastic", themeIplastic);
import themeKatzenmilch from "ace-builds/src-noconflict/theme-katzenmilch?url";
ace.config.setModuleUrl("ace/theme/katzenmilch", themeKatzenmilch);
import themeKrTheme from "ace-builds/src-noconflict/theme-kr_theme?url";
ace.config.setModuleUrl("ace/theme/kr_theme", themeKrTheme);
import themeKuroir from "ace-builds/src-noconflict/theme-kuroir?url";
ace.config.setModuleUrl("ace/theme/kuroir", themeKuroir);
import themeMerbivore from "ace-builds/src-noconflict/theme-merbivore?url";
ace.config.setModuleUrl("ace/theme/merbivore", themeMerbivore);
import themeMerbivoreSoft from "ace-builds/src-noconflict/theme-merbivore_soft?url";
ace.config.setModuleUrl("ace/theme/merbivore_soft", themeMerbivoreSoft);
import themeMonoIndustrial from "ace-builds/src-noconflict/theme-mono_industrial?url";
ace.config.setModuleUrl("ace/theme/mono_industrial", themeMonoIndustrial);
import themeMonokai from "ace-builds/src-noconflict/theme-monokai?url";
ace.config.setModuleUrl("ace/theme/monokai", themeMonokai);
import themeNordDark from "ace-builds/src-noconflict/theme-nord_dark?url";
ace.config.setModuleUrl("ace/theme/nord_dark", themeNordDark);
import themeOneDark from "ace-builds/src-noconflict/theme-one_dark?url";
ace.config.setModuleUrl("ace/theme/one_dark", themeOneDark);
import themePastelOnDark from "ace-builds/src-noconflict/theme-pastel_on_dark?url";
ace.config.setModuleUrl("ace/theme/pastel_on_dark", themePastelOnDark);
import themeSolarizedDark from "ace-builds/src-noconflict/theme-solarized_dark?url";
ace.config.setModuleUrl("ace/theme/solarized_dark", themeSolarizedDark);
import themeSolarizedLight from "ace-builds/src-noconflict/theme-solarized_light?url";
ace.config.setModuleUrl("ace/theme/solarized_light", themeSolarizedLight);
import themeSqlserver from "ace-builds/src-noconflict/theme-sqlserver?url";
ace.config.setModuleUrl("ace/theme/sqlserver", themeSqlserver);
import themeTerminal from "ace-builds/src-noconflict/theme-terminal?url";
ace.config.setModuleUrl("ace/theme/terminal", themeTerminal);
import themeTextmate from "ace-builds/src-noconflict/theme-textmate?url";
ace.config.setModuleUrl("ace/theme/textmate", themeTextmate);
import themeTomorrow from "ace-builds/src-noconflict/theme-tomorrow?url";
ace.config.setModuleUrl("ace/theme/tomorrow", themeTomorrow);
import themeTomorrowNight from "ace-builds/src-noconflict/theme-tomorrow_night?url";
ace.config.setModuleUrl("ace/theme/tomorrow_night", themeTomorrowNight);
import themeTomorrowNightBlue from "ace-builds/src-noconflict/theme-tomorrow_night_blue?url";
ace.config.setModuleUrl(
	"ace/theme/tomorrow_night_blue",
	themeTomorrowNightBlue
);
import themeTomorrowNightBright from "ace-builds/src-noconflict/theme-tomorrow_night_bright?url";
ace.config.setModuleUrl(
	"ace/theme/tomorrow_night_bright",
	themeTomorrowNightBright
);
import themeTomorrowNightEighties from "ace-builds/src-noconflict/theme-tomorrow_night_eighties?url";
ace.config.setModuleUrl(
	"ace/theme/tomorrow_night_eighties",
	themeTomorrowNightEighties
);
import themeTwilight from "ace-builds/src-noconflict/theme-twilight?url";
ace.config.setModuleUrl("ace/theme/twilight", themeTwilight);
import themeVibrantInk from "ace-builds/src-noconflict/theme-vibrant_ink?url";
ace.config.setModuleUrl("ace/theme/vibrant_ink", themeVibrantInk);
import themeXcode from "ace-builds/src-noconflict/theme-xcode?url";
ace.config.setModuleUrl("ace/theme/xcode", themeXcode);

import workerBase from "ace-builds/src-noconflict/worker-base?url";
ace.config.setModuleUrl("ace/mode/base_worker", workerBase);
import workerCoffee from "ace-builds/src-noconflict/worker-coffee?url";
ace.config.setModuleUrl("ace/mode/coffee_worker", workerCoffee);
import workerCss from "ace-builds/src-noconflict/worker-css?url";
ace.config.setModuleUrl("ace/mode/css_worker", workerCss);
import workerHtml from "ace-builds/src-noconflict/worker-html?url";
ace.config.setModuleUrl("ace/mode/html_worker", workerHtml);
import workerJavascript from "ace-builds/src-noconflict/worker-javascript?url";
ace.config.setModuleUrl("ace/mode/javascript_worker", workerJavascript);
import workerJson from "ace-builds/src-noconflict/worker-json?url";
ace.config.setModuleUrl("ace/mode/json_worker", workerJson);
import workerLua from "ace-builds/src-noconflict/worker-lua?url";
ace.config.setModuleUrl("ace/mode/lua_worker", workerLua);
import workerPhp from "ace-builds/src-noconflict/worker-php?url";
ace.config.setModuleUrl("ace/mode/php_worker", workerPhp);
import workerXml from "ace-builds/src-noconflict/worker-xml?url";
ace.config.setModuleUrl("ace/mode/xml_worker", workerXml);
import workerXquery from "ace-builds/src-noconflict/worker-xquery?url";
ace.config.setModuleUrl("ace/mode/xquery_worker", workerXquery);
import workerYaml from "ace-builds/src-noconflict/worker-yaml?url";
ace.config.setModuleUrl("ace/mode/yaml_worker", workerYaml);

export { ace };
