name = "astra-bin"
main = "./src/index.ts"
compatibility_date = "2024-07-12"

workers_dev = false
[[kv_namespaces]]
binding = "pastes"
id = "075576fde0c74d29aa3694ca0d0fe886"
preview_id = "075576fde0c74d29aa3694ca0d0fe886"

[vars]
WORKERS_RS_VERSION = "0.3.0"
MAX_PASTE_LENGTH = "100000"
KEY_LENGTH = "5"
PASTE_TTL = "300"
CLIENT_ORIGIN = "http://localhost:5173"
CONTENT_TYPE_PREFIX = "text/vnd.astra-bin."

[env.staging]
workers_dev = true
name = "astra-bin-staging"

[[env.staging.kv_namespaces]]
binding = "pastes"
id = "075576fde0c74d29aa3694ca0d0fe886"

[env.staging.vars]
WORKERS_RS_VERSION = "0.3.0"
MAX_PASTE_LENGTH = "100000"
KEY_LENGTH = "5"
PASTE_TTL = "300"
CLIENT_ORIGIN = "https://dev.astra-bin.pages.dev"
CONTENT_TYPE_PREFIX = "text/vnd.astra-bin."

[[env.production.kv_namespaces]]
binding = "pastes"
id = "827aefb455974d68b13f83a23736e376"
preview_id = "075576fde0c74d29aa3694ca0d0fe886"

[env.production.vars]
WORKERS_RS_VERSION = "0.3.0"
MAX_PASTE_LENGTH = "100000"
KEY_LENGTH = "5"
PASTE_TTL = "604800"
CLIENT_ORIGIN = "https://bin.thatsnomoon.dev"
CONTENT_TYPE_PREFIX = "text/vnd.astra-bin."

[env.production.route]
custom_domain = true
pattern = "bin-api.thatsnomoon.dev"
